"use client";

import { useMemo, useState, type Dispatch, type SetStateAction } from "react";
import * as XLSX from "xlsx";
import { ArrowDown, ArrowUp, Download, FilePlus2, FileSpreadsheet, Printer, Save, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Heading, Panel, Picker } from "@/components/results-ui";
import { ReportFooter, ReportHeader, reportStyle } from "@/components/report-chrome";
import { EXAMS, bandOf, deltaText, examOf, groups, pct, percent, statusArabic, values, type CustomReportTemplate, type Dimension, type ExamKey, type RecordRow, type Workspace } from "@/lib/results-engine";

type Props = { workspace: Workspace; setWorkspace: Dispatch<SetStateAction<Workspace>> };
type Field = { key: string; label: string };

const dimensions: { value: Dimension; label: string }[] = [{ value: "grade", label: "الصف" }, { value: "className", label: "الشعبة" }, { value: "department", label: "القسم" }, { value: "subject", label: "المادة" }, { value: "teacher", label: "المعلم" }];
const defaultColumns = [{ key: "studentId", label: "الرقم" }, { key: "studentName", label: "اسم الطالب" }, { key: "className", label: "الشعبة" }, { key: "teacher", label: "المعلم" }, { key: "score:exam4", label: "الدرجة" }, { key: "percent:exam4", label: "النسبة" }, { key: "band:exam4", label: "المستوى" }];
const defaultTemplate = (): CustomReportTemplate => ({ id: "", name: "تقرير مخصص جديد", title: "تقرير مخصص", subtitle: "", mode: "detail", groupBy: "className", subject: "الكل", entityDimension: "className", entity: "الكل", exam: "exam4", compareExam: "exam3", minPercent: 0, maxPercent: 100, columns: defaultColumns, orientation: "portrait", footerText: "" });

function fields(workspace: Workspace, mode: CustomReportTemplate["mode"]): Field[] {
  if (mode === "summary") return [{ key: "group", label: "المجموعة" }, { key: "students", label: "عدد الطلاب" }, { key: "evaluated", label: "المقيمون" }, { key: "passed", label: "الناجحون" }, { key: "failed", label: "الراسبون" }, { key: "success", label: "نسبة النجاح" }, { key: "achievement", label: "نسبة التحصيل" }, { key: "valueAdded", label: "القيمة المضافة" }];
  const base = [{ key: "studentId", label: "الرقم الأكاديمي" }, { key: "studentName", label: "اسم الطالب" }, { key: "grade", label: "الصف" }, { key: "className", label: "الشعبة" }, { key: "department", label: "القسم" }, { key: "subject", label: "المادة" }, { key: "teacher", label: "المعلم" }];
  const exams = workspace.settings.exams.flatMap((exam) => [{ key: `score:${exam.key}`, label: `درجة ${exam.name}` }, { key: `status:${exam.key}`, label: `حالة ${exam.name}` }, { key: `percent:${exam.key}`, label: `نسبة ${exam.name}` }, { key: `band:${exam.key}`, label: `مستوى ${exam.name}` }]);
  const deltas = EXAMS.slice(1).map((exam, index) => ({ key: `delta:${EXAMS[index]}:${exam}`, label: `القيمة المضافة ${workspace.settings.exams[index].name} ← ${workspace.settings.exams[index + 1].name}` }));
  return [...base, ...exams, ...deltas];
}

function detailValue(row: RecordRow, key: string, workspace: Workspace): string | number {
  if (["studentId", "studentName", "grade", "className", "department", "subject", "teacher"].includes(key)) return String(row[key as keyof RecordRow] ?? "");
  const [kind, a, b] = key.split(":"); const exam = a as ExamKey;
  if (kind === "score") return row.scores[exam] ?? statusArabic(row.statuses[exam]);
  if (kind === "status") return statusArabic(row.statuses[exam]);
  if (kind === "percent") { const value = pct(row, exam, workspace.settings); return value === null ? "—" : percent(value); }
  if (kind === "band") { const value = pct(row, exam, workspace.settings); return value === null ? statusArabic(row.statuses[exam]) : bandOf(value, workspace.settings.bands)?.label ?? "—"; }
  if (kind === "delta") { const from = pct(row, a as ExamKey, workspace.settings), to = pct(row, b as ExamKey, workspace.settings); return from === null || to === null ? "—" : deltaText(to - from); }
  return "";
}

export function CustomReportBuilder({ workspace, setWorkspace }: Props) {
  const [template, setTemplate] = useState<CustomReportTemplate>(defaultTemplate);
  const [fieldToAdd, setFieldToAdd] = useState("studentName");
  const available = fields(workspace, template.mode);
  const sourceRows = useMemo(() => workspace.rows.filter((row) => (template.subject === "الكل" || row.subject === template.subject) && (template.entity === "الكل" || row[template.entityDimension] === template.entity)).filter((row) => { const value = pct(row, template.exam, workspace.settings); return value === null || (value >= template.minPercent && value <= template.maxPercent); }), [workspace, template.subject, template.entity, template.entityDimension, template.exam, template.minPercent, template.maxPercent]);
  const output = useMemo(() => {
    if (template.mode === "detail") return sourceRows.map((row) => Object.fromEntries(template.columns.map((column) => [column.key, detailValue(row, column.key, workspace)])));
    return groups(sourceRows, template.groupBy, template.exam, workspace.settings, template.compareExam === template.exam ? null : template.compareExam).map((item) => Object.fromEntries(template.columns.map((column) => [column.key, ({ group: item.name, students: item.metric.students, evaluated: item.metric.evaluated, passed: item.metric.passed, failed: item.metric.failed, success: percent(item.metric.success), achievement: percent(item.metric.achievement), valueAdded: item.va ? deltaText(item.va.delta) : "خط أساس" } as Record<string, string | number>)[column.key] ?? ""])));
  }, [sourceRows, template.mode, template.groupBy, template.exam, template.compareExam, template.columns, workspace]);
  const pageSize = template.orientation === "landscape" ? 22 : 30;
  const pages = output.length ? Array.from({ length: Math.ceil(output.length / pageSize) }, (_, index) => output.slice(index * pageSize, (index + 1) * pageSize)) : [[]];
  const entityValues = values(workspace.rows.filter((row) => template.subject === "الكل" || row.subject === template.subject), template.entityDimension);
  const update = (patch: Partial<CustomReportTemplate>) => setTemplate((current) => ({ ...current, ...patch }));
  const reset = () => { setTemplate(defaultTemplate()); setFieldToAdd("studentName"); };
  const load = (id: string) => { const saved = workspace.customReports.find((item) => item.id === id); if (saved) setTemplate({ ...saved, columns: saved.columns.map((column) => ({ ...column })) }); };
  const save = () => {
    if (!template.name.trim() || !template.title.trim() || !template.columns.length) { toast.error("أدخل اسم التقرير وعنوانه واختر عمودًا واحدًا على الأقل"); return; }
    const item = { ...template, id: template.id || crypto.randomUUID(), columns: template.columns.map((column) => ({ ...column })) };
    setWorkspace((current) => ({ ...current, customReports: [...current.customReports.filter((saved) => saved.id !== item.id), item] })); setTemplate(item); toast.success("تم حفظ قالب التقرير");
  };
  const remove = () => { if (!template.id) return; setWorkspace((current) => ({ ...current, customReports: current.customReports.filter((item) => item.id !== template.id) })); reset(); toast.success("تم حذف القالب"); };
  const exportExcel = () => { const book = XLSX.utils.book_new(), rows = output.map((row) => Object.fromEntries(template.columns.map((column) => [column.label, row[column.key] ?? ""]))); XLSX.utils.book_append_sheet(book, XLSX.utils.json_to_sheet(rows), "التقرير"); XLSX.writeFile(book, `${template.name || "تقرير-مخصص"}.xlsx`); };
  const exportCsv = () => { const rows = output.map((row) => Object.fromEntries(template.columns.map((column) => [column.label, row[column.key] ?? ""]))), csv = XLSX.utils.sheet_to_csv(XLSX.utils.json_to_sheet(rows)), blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" }), url = URL.createObjectURL(blob), link = document.createElement("a"); link.href = url; link.download = `${template.name || "تقرير-مخصص"}.csv`; link.click(); URL.revokeObjectURL(url); };
  const move = (index: number, direction: -1 | 1) => { const next = [...template.columns], target = index + direction; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; update({ columns: next }); };
  return <div className="space-y-6">
    <div className="custom-report-screen-only"><Heading kicker="مدخلات ومخرجات تحت سيطرتك" title="منشئ التقارير المخصصة" desc="اختر البيانات والحسابات والترتيب والترويسة والعنوان والتذييل، ثم احفظ القالب واطبعه أو صدّره." action={<div className="flex flex-wrap gap-2"><Button variant="outline" onClick={reset}><FilePlus2/>تقرير جديد</Button><Button onClick={save} className="bg-teal-700"><Save/>حفظ القالب</Button></div>}/></div>
    <div className="custom-report-screen-only grid gap-5 xl:grid-cols-[.72fr_1.28fr]">
      <div className="space-y-5">
        <Panel title="القوالب المحفوظة"><Picker className="w-full" value={template.id || "__new__"} onChange={(value) => value === "__new__" ? reset() : load(value)} items={[{ value: "__new__", label: "تقرير جديد" }, ...workspace.customReports.map((item) => ({ value: item.id, label: item.name }))]}/>{template.id && <Button variant="outline" className="mt-3 w-full border-rose-200 text-rose-700" onClick={remove}><Trash2/>حذف القالب الحالي</Button>}</Panel>
        <Panel title="هوية التقرير"><div className="grid gap-4"><div><Label>اسم القالب</Label><Input className="mt-2" value={template.name} onChange={(e) => update({ name: e.target.value })}/></div><div><Label>عنوان التقرير</Label><Input className="mt-2" value={template.title} onChange={(e) => update({ title: e.target.value })}/></div><div><Label>عنوان فرعي</Label><Input className="mt-2" value={template.subtitle} onChange={(e) => update({ subtitle: e.target.value })}/></div><div><Label>تذييل خاص بهذا التقرير</Label><Textarea className="mt-2" value={template.footerText} onChange={(e) => update({ footerText: e.target.value })}/></div></div></Panel>
        <Panel title="مصدر البيانات"><div className="grid gap-4 sm:grid-cols-2"><div><Label>نوع التقرير</Label><Picker className="mt-2 w-full" value={template.mode} onChange={(value) => update({ mode: value as "detail" | "summary", columns: value === "summary" ? fields(workspace, "summary").slice(0, 8) : defaultColumns })} items={[{ value: "detail", label: "سجلات الطلاب" }, { value: "summary", label: "ملخصات مجمعة" }]}/></div>{template.mode === "summary" && <div><Label>التجميع حسب</Label><Picker className="mt-2 w-full" value={template.groupBy} onChange={(value) => update({ groupBy: value as Dimension })} items={dimensions}/></div>}<div><Label>المادة</Label><Picker className="mt-2 w-full" value={template.subject} onChange={(value) => update({ subject: value, entity: "الكل" })} items={[{ value: "الكل", label: "كل المواد" }, ...values(workspace.rows, "subject").map((value) => ({ value, label: value }))]}/></div><div><Label>نطاق التصفية</Label><Picker className="mt-2 w-full" value={template.entityDimension} onChange={(value) => update({ entityDimension: value as Dimension, entity: "الكل" })} items={dimensions}/></div><div className="sm:col-span-2"><Label>القيمة المحددة</Label><Picker className="mt-2 w-full" value={entityValues.includes(template.entity) ? template.entity : "الكل"} onChange={(value) => update({ entity: value })} items={[{ value: "الكل", label: "الكل" }, ...entityValues.map((value) => ({ value, label: value }))]}/></div><div><Label>الاختبار الرئيسي</Label><Picker className="mt-2 w-full" value={template.exam} onChange={(value) => update({ exam: value as ExamKey })} items={workspace.settings.exams.map((exam) => ({ value: exam.key, label: exam.name }))}/></div><div><Label>اختبار المقارنة</Label><Picker className="mt-2 w-full" value={template.compareExam} onChange={(value) => update({ compareExam: value as ExamKey })} items={workspace.settings.exams.map((exam) => ({ value: exam.key, label: exam.name }))}/></div><div><Label>من نسبة</Label><Input className="mt-2" type="number" min="0" max="100" value={template.minPercent} onChange={(e) => update({ minPercent: Number(e.target.value) })}/></div><div><Label>إلى نسبة</Label><Input className="mt-2" type="number" min="0" max="100" value={template.maxPercent} onChange={(e) => update({ maxPercent: Number(e.target.value) })}/></div><div className="sm:col-span-2"><Label>اتجاه الصفحة</Label><Picker className="mt-2 w-full" value={template.orientation} onChange={(value) => update({ orientation: value as "portrait" | "landscape" })} items={[{ value: "portrait", label: "A4 طولي" }, { value: "landscape", label: "A4 عرضي" }]}/></div></div></Panel>
      </div>
      <div className="space-y-5">
        <Panel title="اختيار أعمدة التقرير" desc="يمكن تغيير اسم كل عمود وترتيبه وإضافة ما تحتاجه فقط."><div className="flex flex-col gap-2 sm:flex-row"><Picker className="min-w-0 flex-1" value={available.some((item) => item.key === fieldToAdd) ? fieldToAdd : available[0]?.key ?? ""} onChange={setFieldToAdd} items={available.map((item) => ({ value: item.key, label: item.label }))}/><Button onClick={() => { const field = available.find((item) => item.key === fieldToAdd); if (field && !template.columns.some((item) => item.key === field.key)) update({ columns: [...template.columns, { ...field }] }); }}><FilePlus2/>إضافة العمود</Button></div><div className="mt-4 space-y-2">{template.columns.map((column, index) => <div key={column.key} className="flex items-center gap-2 rounded-xl border bg-slate-50 p-2"><span className="grid size-8 place-items-center rounded-lg bg-white text-xs font-black">{index + 1}</span><Input value={column.label} onChange={(e) => update({ columns: template.columns.map((item) => item.key === column.key ? { ...item, label: e.target.value } : item) })}/><Button size="icon" variant="ghost" onClick={() => move(index, -1)} title="تحريك لأعلى"><ArrowUp/></Button><Button size="icon" variant="ghost" onClick={() => move(index, 1)} title="تحريك لأسفل"><ArrowDown/></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => update({ columns: template.columns.filter((item) => item.key !== column.key) })} title="إزالة"><X/></Button></div>)}</div></Panel>
        <Panel title="المخرجات" desc={`${output.length.toLocaleString("ar-EG")} سجل في ${pages.length.toLocaleString("ar-EG")} صفحة`}><div className="grid gap-3 sm:grid-cols-3"><Button onClick={() => window.print()} className="bg-[#123247]"><Printer/>طباعة / PDF</Button><Button variant="outline" onClick={exportExcel}><FileSpreadsheet/>Excel</Button><Button variant="outline" onClick={exportCsv}><Download/>CSV</Button></div><div className="mt-4 flex flex-wrap gap-2"><Badge variant="outline">{template.mode === "detail" ? "تفصيلي" : `تجميع حسب ${dimensions.find((item) => item.value === template.groupBy)?.label}`}</Badge><Badge variant="outline">{examOf(workspace.settings, template.exam).name}</Badge><Badge variant="outline">{template.orientation === "portrait" ? "طولي" : "عرضي"}</Badge></div></Panel>
      </div>
    </div>
    <div className="report-preview-shell"><div id="custom-printable-reports" className="print-zone">{pages.map((page, pageIndex) => <section key={pageIndex} className={`school-report-page custom-report-page ${template.orientation === "landscape" ? "landscape" : "portrait"}`} style={reportStyle(workspace)}><ReportHeader workspace={workspace} title={`${template.title}${pages.length > 1 ? ` — الجزء ${pageIndex + 1} من ${pages.length}` : ""}`} subject={template.subject === "الكل" ? "كل المواد" : template.subject} assessment={examOf(workspace.settings, template.exam).name}/>{template.subtitle && <p className="custom-report-subtitle">{template.subtitle}</p>}<table className="report-table custom-report-table"><thead><tr>{template.columns.map((column) => <th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{page.length ? page.map((row, index) => <tr key={index}>{template.columns.map((column) => <td key={column.key}>{row[column.key]}</td>)}</tr>) : <tr><td colSpan={Math.max(1, template.columns.length)}>لا توجد بيانات تطابق الاختيارات.</td></tr>}</tbody></table><ReportFooter workspace={workspace} subject={template.subject === "الكل" ? "" : template.subject} customFooter={template.footerText}/><span className="report-page-number">صفحة {pageIndex + 1} من {pages.length}</span></section>)}</div></div>
  </div>;
}
